/**
 * Family-friendly starter deck. PG on purpose: no crude, romantic, or adult jokes.
 * The host still sees whatever players type, so a grown-up should be in the room.
 */
export const PROMPTS = [
  "What's the real reason grandma's Wi-Fi is slow?",
  "Why did the family dog call a family meeting?",
  "What did Uncle Dave actually do with the leftover pie?",
  "What's the secret ingredient in Mom's famous chili?",
  "Why is the minivan making that noise again?",
  "What is Dad really doing out in the garage?",
  "Why did the cat knock the plant off the shelf this time?",
  "What does the note on the fridge say that nobody will read out loud?",
  "Why did the school bus driver pull over and sigh?",
  "What did the toddler try to mail to the president?",
  "Why is the holiday turkey still frozen?",
  "What new house rule did the kids invent while the adults were outside?",
  "Why did the goldfish look so judgmental?",
  "What's the real reason the family photo is blurry?",
  "What did Grandpa hide in the junk drawer?",
  "Why did the robot vacuum refuse to work overtime?",
  "What's the password hint for the family tablet?",
  "Why did the picnic get moved indoors on a sunny day?",
  "What did the parrot learn at Thanksgiving and refuse to forget?",
  "Why is there a single sneaker on the roof?",
  "What did the librarian say when the book came back four years late?",
  "Why did the snowman file a complaint with the neighbors?",
  "What's the real reason the cookies vanished before the party?",
  "What is the dog's campaign slogan for best family member?",
  "Why did the alarm clock go off at 3 a.m. and then apologize?",
  "What did the substitute teacher write on the board by mistake?",
  "Why did the suitcase look ready to leave without anyone?",
  "What's hiding in the couch cushions besides coins?",
  "Why did the family group chat go quiet for six whole hours?",
  "What did the raccoon pitch at the city council meeting?",
  "Why is the birthday cake leaning like that?",
  "What extra rule did the board game grow after bedtime?",
  "Why did the houseplant write a strongly worded letter?",
  "What's the real reason the Wi-Fi has a password now?",
  "What did the little league team chant instead of their team name?",
  "Why did the GPS say it was not mad, just disappointed?",
  "What did Aunt June bring to the potluck that nobody can identify?",
  "Why did the hamster start a tiny podcast?",
  "What's the title of the movie the kids filmed on the tablet?",
  "Why did the refrigerator light stay on and stare at everyone?",
];
